version: '3.8'

services:
  movie_reco:
    container_name : llm_server
    volumes:
      - .:/app/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "python main.py"
